In [1]:
import unicodecsv as csv
import pandas as pd

In [4]:
df = pd.DataFrame.from_csv("USCities.csv")

# create year column for grouping
df["year"] = df["dt"].apply(lambda x: x[:4])

df.drop_duplicates(subset=["Latitude", "Longitude", "year"], inplace=True)
del df["dt"]
del df["Country"]

df["AverageTemperature"] = pd.to_numeric(df["AverageTemperature"], errors="coerce")

df.groupby(["year", "City", "Latitude"])["AverageTemperature"].mean()
df.sort_values(by=["year", "City"], inplace=True)
df.to_csv("USCityAverageTempByYear.csv")

In [5]:
df

         AverageTemperature            City Latitude Longitude  year
49236                 5.243         Abilene   32.95N   100.53W  1960
139661               -0.832           Akron   40.99N    80.95W  1960
169756               -2.360     Albuquerque   34.56N   107.03W  1960
190123                1.377      Alexandria   39.38N    76.99W  1960
204846               -1.593       Allentown   40.99N    74.56W  1960
233383                1.946        Amarillo   34.56N   101.19W  1960
275585               11.832         Anaheim   32.95N   117.77W  1960
287138              -12.961       Anchorage   61.88N   151.13W  1960
317552               -3.128       Ann Arbor   42.59N    82.91W  1960
336240                8.238         Antioch   37.78N   122.03W  1960
402717                6.501       Arlington   32.95N    96.70W  1960
418989               -8.273          Arvada   39.38N   106.13W  1960
468899                5.157         Atlanta   34.56N    83.68W  1960
484374               -4.577          Aurora   39.38N   104.05W  1960
487613               -2.607          Aurora   40.99N    87.34W  1960
489938                9.678          Austin   29.74N    97.85W  1960
574792                6.587     Bakersfield   36.17N   119.34W  1960
752422               11.204     Baton Rouge   29.74N    90.46W  1960
766044               10.487        Beaumont   29.74N    94.15W  1960
810618                0.183        Bellevue   47.42N   121.97W  1960
983227                6.951      Birmingham   32.95N    87.13W  1960
1058341              -4.812          Boston   42.59N    72.00W  1960
1136222               0.264      Bridgeport   40.99N    72.43W  1960
1154159              17.033     Brownsville   26.52N    96.72W  1960
1183987              -3.770         Buffalo   42.59N    78.55W  1960
1211737               7.533         Burbank   34.56N   118.70W  1960
1355704              18.496      Cape Coral   26.52N    82.39W  1960
1394266               4.510            Cary   36.17N    79.56W  1960
1424503              -6.400    Cedar Rapids   42.59N    91.64W  1960
1443519               8.487        Chandler   32.95N   112.02W  1960
...                     ...             ...      ...       ...   ...
4764074               6.944         Memphis   34.56N    89.51W  2013
4839594             -10.730     Minneapolis   45.81N    93.46W  2013
4873227              11.824          Mobile   31.35N    88.59W  2013
4880336               3.579         Modesto   37.78N   120.00W  2013
5224114               4.049    Newport News   37.78N    77.29W  2013
5297881               7.764         Nogales   31.35N   111.20W  2013
5311910               6.381          Norman   34.56N    97.30W  2013
5435571               4.250   Oklahoma City   36.17N    97.46W  2013
5443770              -0.162          Olathe   39.38N    95.72W  2013
5511416              19.270         Orlando   28.13N    80.91W  2013
5786761              -2.831          Peoria   40.99N    89.47W  2013
5849440               2.252    Philadelphia   39.38N    74.91W  2013
5991232               3.086        Portland   45.81N   123.46W  2013
6060155              -7.446           Provo   39.38N   112.37W  2013
6072068              -1.044          Pueblo   37.78N   103.73W  2013
6318072               2.565            Reno   39.38N   120.69W  2013
6542420              -0.280     Saint Louis   39.38N    89.48W  2013
6583156               8.914         Salinas   36.17N   121.33W  2013
6585459              -6.577  Salt Lake City   40.99N   112.90W  2013
6818746              15.317        Savannah   31.35N    81.05W  2013
6979448               8.663      Shreveport   32.95N    92.87W  2013
7037791              -8.664     Sioux Falls   44.20N    96.15W  2013
7136965              -2.837         Spokane   47.42N   117.24W  2013
7142177               2.125     Springfield   37.78N    93.56W  2013
7305936              -2.724        Syracuse   42.59N    76.36W  2013
7395517              16.233     Tallahassee   29.74N    84.92W  2013
7666406              -1.714          Toledo   40.99N    83.08W  2013
7794838               4.408           Tulsa   36.17N    95.47W  2013
8213350               1.628         Wichita   37.78N    97.63W  2013
8215675               5.317   Wichita Falls   34.56N    99.24W  2013

[5238 rows x 5 columns]